# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # Pipe Frontend
      - name: Install dependencies
        run: |
          cd frontend && npm install

      - name: Tests
        run: |
            cd frontend
            npm test
            
      - name: Lint
        run: |
          cd frontend
          npm run lint


      # Pipe Backend    
      - name: Install dependencies
        run: |
          cd backend; npm install

      - name: Tests
        run: |
            cd backend; npm test
      - name: Lint
        run: |
          cd backend; npm run lint
